var s_iScaleFactor=1,s_bIsIphone=!1;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isIOS(){var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");for(-1!==navigator.userAgent.toLowerCase().indexOf("iphone")&&(s_bIsIphone=!0);a.length;)if(navigator.platform===a.pop())return!0;return s_bIsIphone=!1}
function getSize(a){var d=a.toLowerCase(),f=window.document,b=f.documentElement;if(void 0===window["inner"+a])a=b["client"+a];else if(window["inner"+a]!=b["client"+a]){var g=f.createElement("body");g.id="vpw-test-b";g.style.cssText="overflow:scroll";var e=f.createElement("div");e.id="vpw-test-d";e.style.cssText="position:absolute;top:-1000px";e.innerHTML="<style>@media("+d+":"+b["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+d+":7px!important}}</style>";g.appendChild(e);b.insertBefore(g,f.head);
a=7==e["offset"+a]?b["client"+a]:window["inner"+a];b.removeChild(g)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var d=getSize("Width");_checkOrientation(d,a);var f=Math.min(a/CANVAS_HEIGHT,d/CANVAS_WIDTH),b=CANVAS_WIDTH*f,f=CANVAS_HEIGHT*f,g;f<a?(g=a-f,f+=g,b+=CANVAS_WIDTH/CANVAS_HEIGHT*g):b<d&&(g=d-b,b+=g,f+=CANVAS_HEIGHT/CANVAS_WIDTH*g);g=a/2-f/2;var e=d/2-b/2,l=CANVAS_WIDTH/b;if(e*l<-EDGEBOARD_X||g*l<-EDGEBOARD_Y)f=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),
d/(CANVAS_WIDTH-2*EDGEBOARD_X)),b=CANVAS_WIDTH*f,f*=CANVAS_HEIGHT,g=(a-f)/2,e=(d-b)/2,l=CANVAS_WIDTH/b;s_iOffsetX=-1*e*l;s_iOffsetY=-1*g*l;0<=g&&(s_iOffsetY=0);0<=e&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bIsIphone?(canvas=document.getElementById("canvas"),s_oStage.canvas.width=2*b,s_oStage.canvas.height=2*f,canvas.style.width=b+"px",canvas.style.height=f+"px",a=Math.min(b/CANVAS_WIDTH,
f/CANVAS_HEIGHT),s_iScaleFactor=2*a,s_oStage.scaleX=s_oStage.scaleY=2*a):s_bMobile&&!1===isIOS()?($("#canvas").css("width",b+"px"),$("#canvas").css("height",f+"px")):(s_oStage.canvas.width=b,s_oStage.canvas.height=f,s_iScaleFactor=Math.min(b/CANVAS_WIDTH,f/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0>g?$("#canvas").css("top",g+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",e+"px")}}
function _checkOrientation(a,d){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>d?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function inIframe(){try{return window.self!==window.top}catch(a){return!0}}function createBitmap(a,d,f){var b=new createjs.Bitmap(a),g=new createjs.Shape;d&&f?g.graphics.beginFill("#fff").drawRect(0,0,d,f):g.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);b.hitArea=g;return b}function createSprite(a,d,f,b,g,e){a=null!==d?new createjs.Sprite(a,d):new createjs.Sprite(a);d=new createjs.Shape;d.graphics.beginFill("#000000").drawRect(-f,-b,g,e);a.hitArea=d;return a}
function randomFloatBetween(a,d,f){"undefined"===typeof f&&(f=2);return parseFloat(Math.min(a+Math.random()*(d-a),d).toFixed(f))}function shuffle(a){for(var d=a.length,f,b;0!==d;)b=Math.floor(Math.random()*d),--d,f=a[d],a[d]=a[b],a[b]=f;return a}function formatTime(a){a/=1E3;var d=Math.floor(a/60);a=parseFloat(a-60*d).toFixed(1);var f="",f=10>d?f+("0"+d+":"):f+(d+":");return 10>a?f+("0"+a):f+a}
function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3===a.nodeType&&(a=a.parentNode);var d=document.createEvent("MouseEvents");d.initEvent("click",!0,!0);a.dispatchEvent(d)}}};function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var d=window.location.search.substring(1).split("&"),f=0;f<d.length;f++){var b=d[f].split("=");if(b[0]==a)return b[1]}}
(function(){function a(a){var b={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in b?document.body.className=b[a.type]:(document.body.className=this[d]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var d="hidden";d in document?document.addEventListener("visibilitychange",a):(d="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(d="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(d="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();
function CSpriteLibrary(){var a,d,f,b,g,e;this.init=function(l,h,k){f=d=0;b=l;g=h;e=k;a={}};this.addSprite=function(b,h){a.hasOwnProperty(b)||(a[b]={szPath:h,oSprite:new Image},d++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){g.call(e)};this._onSpriteLoaded=function(){b.call(e);++f===d&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return d}}
var CANVAS_WIDTH=1500,CANVAS_HEIGHT=640,EDGEBOARD_X=300,EDGEBOARD_Y=0,FONT_GAME="adonaisregular",FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,GAME_STATE_IDLE=0,GAME_STATE_SPINNING=1,GAME_STATE_SHOW_ALL_WIN=2,GAME_STATE_SHOW_WIN=3,REEL_STATE_START=0,REEL_STATE_MOVING=1,REEL_STATE_STOP=2,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,REEL_OFFSET_X=380,REEL_OFFSET_Y=118,NUM_REELS=5,NUM_ROWS=3,NUM_SYMBOLS=10,
WILD_SYMBOL=10,BONUS_SYMBOL=9,NUM_PAYLINES=5,SYMBOL_SIZE=140,SPACE_BETWEEN_SYMBOLS=10,MAX_FRAMES_REEL_EASE=16,MIN_REEL_LOOPS,REEL_DELAY,REEL_START_Y=REEL_OFFSET_Y-3*SYMBOL_SIZE,REEL_ARRIVAL_Y=REEL_OFFSET_Y+3*SYMBOL_SIZE,TIME_SHOW_WIN,TIME_SHOW_ALL_WINS,MIN_BET,MAX_BET,TOTAL_MONEY,MAX_NUM_HOLD,BONUS_ITEM_WIDTH=304,BONUS_ITEM_HEIGHT=250,NUM_PRIZES=3,NUM_SYMBOLS_FOR_BONUS=3,PERC_WIN_PRIZE_1,PERC_WIN_PRIZE_2,PERC_WIN_PRIZE_3,SOUNDTRACK_VOLUME=.5,WIN_OCCURRENCE,SLOT_CASH,MIN_WIN,BONUS_OCCURRENCE,PAYTABLE_VALUES,
ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION,SHOW_CREDITS,BONUS_PRIZE=[];
function CSlotSettings(){this._init=function(){this._initSymbolSpriteSheets();this._initPaylines();this._initSymbolWin();this._initSymbolAnims();this._initSymbolsOccurence();this._initBonus()};this._initSymbolSpriteSheets=function(){s_aSymbolData=[];for(var a=1;a<NUM_SYMBOLS+1;a++){var d={images:[s_oSpriteLibrary.getSprite("symbol_"+a)],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],moving:[1,2]}};s_aSymbolData[a]=new createjs.SpriteSheet(d)}};this._initPaylines=
function(){s_aPaylineCombo=[[{row:1,col:0},{row:1,col:1},{row:1,col:2},{row:1,col:3},{row:1,col:4}],[{row:0,col:0},{row:0,col:1},{row:0,col:2},{row:0,col:3},{row:0,col:4}],[{row:2,col:0},{row:2,col:1},{row:2,col:2},{row:2,col:3},{row:2,col:4}],[{row:0,col:0},{row:1,col:1},{row:2,col:2},{row:1,col:3},{row:0,col:4}],[{row:2,col:0},{row:1,col:1},{row:0,col:2},{row:1,col:3},{row:2,col:4}]]};this._initSymbolAnims=function(){s_aSymbolAnims=[];var a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_1_anim")],
frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[0]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_2_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[1]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_3_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,
1],anim:[1,14]}};s_aSymbolAnims[2]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_4_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[3]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_5_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[4]=new createjs.SpriteSheet(a);a={framerate:20,
images:[s_oSpriteLibrary.getSprite("symbol_6_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[5]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_7_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[6]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_8_anim")],frames:{width:SYMBOL_SIZE,
height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[7]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_9_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[8]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_10_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,
14]}};s_aSymbolAnims[9]=new createjs.SpriteSheet(a)};this._initSymbolWin=function(){s_aSymbolWin=[];s_aSymbolWin[0]=PAYTABLE_VALUES[0];s_aSymbolWin[1]=PAYTABLE_VALUES[1];s_aSymbolWin[2]=PAYTABLE_VALUES[2];s_aSymbolWin[3]=PAYTABLE_VALUES[3];s_aSymbolWin[4]=PAYTABLE_VALUES[4];s_aSymbolWin[5]=PAYTABLE_VALUES[5];s_aSymbolWin[6]=PAYTABLE_VALUES[6];s_aSymbolWin[7]=PAYTABLE_VALUES[7]};this._initSymbolsOccurence=function(){s_aRandSymbols=[];var a;for(a=0;1>a;a++)s_aRandSymbols.push(1);for(a=0;2>a;a++)s_aRandSymbols.push(2);
for(a=0;3>a;a++)s_aRandSymbols.push(3);for(a=0;4>a;a++)s_aRandSymbols.push(4);for(a=0;4>a;a++)s_aRandSymbols.push(5);for(a=0;6>a;a++)s_aRandSymbols.push(6);for(a=0;7>a;a++)s_aRandSymbols.push(7);for(a=0;7>a;a++)s_aRandSymbols.push(8);for(a=0;2>a;a++)s_aRandSymbols.push(9);for(a=0;2>a;a++)s_aRandSymbols.push(10)};this._initBonus=function(){s_aPrizeOccurence=[];var a;for(a=0;a<PERC_WIN_PRIZE_1;a++)s_aPrizeOccurence.push(0);for(a=0;a<PERC_WIN_PRIZE_2;a++)s_aPrizeOccurence.push(1);for(a=0;a<PERC_WIN_PRIZE_3;a++)s_aPrizeOccurence.push(2)};
this._init()}var s_aSymbolData,s_aPaylineCombo,s_aSymbolWin,s_aSymbolAnims,s_aRandSymbols,s_aPrizeOccurence;TEXT_MONEY="MONEY";TEXT_PLAY="PLAY";TEXT_BET="BET";TEXT_COIN="COIN";TEXT_MAX_BET="MAX BET";TEXT_INFO="INFO";TEXT_LINES="LINES";TEXT_SPIN="SPIN";TEXT_WIN="WIN";TEXT_HOLD="HOLD";TEXT_HELP_WILD="JOLLY SYMBOL CAN REPLACE ANY OTHER SYMBOL TO MAKE UP A COMBO";TEXT_HELP_BONUS="3 OR MORE PYRAMIDS LET YOU PLAY THE BONUS GAME!";TEXT_CREDITS_DEVELOPED="DEVELOPED BY";TEXT_CURRENCY="$";
TEXT_CONGRATULATIONS="Congratulations!";TEXT_MSG_SHARE1="You collected <strong>";TEXT_MSG_SHARE2=" points</strong>!<br><br>Share your score with your friends!";TEXT_MSG_SHARING1="My score is ";TEXT_MSG_SHARING2=" points! Can you do better?";
function CPreloader(){var a,d,f,b,g,e,l;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_preloader","./sprites/bg_preloader.jpg");s_oSpriteLibrary.addSprite("preloader_bar","./sprites/preloader_bar.png");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();l=new createjs.Container;s_oStage.addChild(l)};this.unload=function(){l.removeAllChildren()};this.hide=function(){var a=
this;setTimeout(function(){createjs.Tween.get(e).to({alpha:1},500).call(function(){a.unload();s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var h=createBitmap(s_oSpriteLibrary.getSprite("bg_preloader"));l.addChild(h);h=s_oSpriteLibrary.getSprite("preloader_bar");f=createBitmap(h);f.x=510;f.y=CANVAS_HEIGHT-131;l.addChild(f);b=createBitmap(s_oSpriteLibrary.getSprite("progress_bar"));
b.x=511;b.y=CANVAS_HEIGHT-130;l.addChild(b);a=h.width;g=new createjs.Shape;g.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(511,CANVAS_HEIGHT-130,1,30);l.addChild(g);b.mask=g;d=new createjs.Text("","24px "+FONT_GAME,"#fff");d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT-108;d.shadow=new createjs.Shadow("#000",2,2,2);d.textBaseline="alphabetic";d.textAlign="center";l.addChild(d);e=new createjs.Shape;e.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);e.alpha=0;l.addChild(e)};this.refreshLoader=
function(b){d.text=b+"%";g.graphics.clear();b=Math.floor(b*a/100);g.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(511,CANVAS_HEIGHT-130,b,30)};this._init()}
function CMain(a){var d,f=0,b=0,g=STATE_LOADING,e,l,h;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&s_oStage.enableMouseOver(20);s_iPrevTime=(new Date).getTime();createjs.Ticker.setFPS(30);createjs.Ticker.addEventListener("tick",this._update);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;l=new CPreloader};
this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();d=!0};this.soundLoaded=function(){f++;f===b&&this._onRemovePreloader()};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/press_but.ogg",
"press_but"),createjs.Sound.registerSound("./sounds/win.ogg","win"),createjs.Sound.registerSound("./sounds/reels.ogg","reels"),createjs.Sound.registerSound("./sounds/reel_stop.ogg","reel_stop",6),createjs.Sound.registerSound("./sounds/start_reel.ogg","start_reel",6),createjs.Sound.registerSound("./sounds/choose_bonus_item.ogg","choose_bonus_item"),createjs.Sound.registerSound("./sounds/press_hold.ogg","press_hold"),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack")):(createjs.Sound.alternateExtensions=
["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/press_but.mp3","press_but"),createjs.Sound.registerSound("./sounds/win.mp3","win"),createjs.Sound.registerSound("./sounds/reels.mp3","reels"),createjs.Sound.registerSound("./sounds/reel_stop.mp3","reel_stop",6),createjs.Sound.registerSound("./sounds/start_reel.mp3","start_reel",6),createjs.Sound.registerSound("./sounds/choose_bonus_item.mp3","choose_bonus_item"),createjs.Sound.registerSound("./sounds/press_hold.mp3",
"press_hold"),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack")),b+=8)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("paytable","./sprites/paytable.jpg");s_oSpriteLibrary.addSprite("but_play_bg","./sprites/but_play_bg.png");
s_oSpriteLibrary.addSprite("mask_slot","./sprites/mask_slot.png");s_oSpriteLibrary.addSprite("spin_but","./sprites/but_spin_bg.png");s_oSpriteLibrary.addSprite("coin_but","./sprites/but_coin_bg.png");s_oSpriteLibrary.addSprite("info_but","./sprites/but_info_bg.png");s_oSpriteLibrary.addSprite("bet_but","./sprites/bet_but.png");s_oSpriteLibrary.addSprite("win_frame_anim","./sprites/win_frame_anim.png");s_oSpriteLibrary.addSprite("but_lines_bg","./sprites/but_lines_bg.png");s_oSpriteLibrary.addSprite("but_maxbet_bg",
"./sprites/but_maxbet_bg.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("hit_area_col","./sprites/hit_area_col.png");s_oSpriteLibrary.addSprite("hold_col","./sprites/hold_col.png");s_oSpriteLibrary.addSprite("bonus_bg","./sprites/bonus_bg.jpg");s_oSpriteLibrary.addSprite("bonus_item","./sprites/bonus_item.png");s_oSpriteLibrary.addSprite("bonus_prize","./sprites/bonus_prize.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");
s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("logo_ctl","./sprites/logo_ctl.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");for(var a=1;a<NUM_SYMBOLS+1;a++)s_oSpriteLibrary.addSprite("symbol_"+a,"./sprites/symbol_"+a+".png"),s_oSpriteLibrary.addSprite("symbol_"+a+"_anim","./sprites/symbol_"+a+"_anim.png");for(a=1;a<NUM_PAYLINES+1;a++)s_oSpriteLibrary.addSprite("payline_"+a,"./sprites/payline_"+a+".png");b+=s_oSpriteLibrary.getNumSprites();
s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){f++;l.refreshLoader(Math.floor(f/b*100));f===b&&this._onRemovePreloader()};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this._onRemovePreloader=function(){l.unload();isIOS()||!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||(s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1}));this.gotoMenu()};this.gotoMenu=function(){new CMenu;g=STATE_MENU};this.gotoGame=function(){h=new CGame(e);
g=STATE_GAME};this.gotoHelp=function(){new CHelp;g=STATE_HELP};this.stopUpdate=function(){d=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");createjs.Sound.setMute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();d=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");s_bAudioActive&&createjs.Sound.setMute(!1)};this._update=function(a){if(!1!==d){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=
b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);g===STATE_GAME&&h.update();s_oStage.update(a)}};s_oMain=this;e=a;PAYTABLE_VALUES=[];for(var k=0;8>k;k++)PAYTABLE_VALUES[k]=a["paytable_symbol_"+(k+1)];ENABLE_CHECK_ORIENTATION=a.check_orientation;SHOW_CREDITS=e.show_credits;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack=null,s_bFullscreen=!1;
function CTextButton(a,d,f,b,g,e,l){var h,k,n,c,u,m,q,p;this._init=function(a,b,e,d,f,l,g){h=!1;c=[];u=[];p=createBitmap(e);k=e.width;n=e.height;q=new createjs.Text(d,g+"px "+f,l);q.textAlign="center";q.shadow=new createjs.Shadow("#000",2,2,2);q.textBaseline="middle";q.lineHeight=24;q.x=e.width/2;q.y=e.height/2;m=new createjs.Container;m.x=a;m.y=b;m.regX=e.width/2;m.regY=e.height/2;m.addChild(p,q);m.cursor="pointer";s_oStage.addChild(m);this._initListener()};this.unload=function(){m.off("mousedown");
m.off("pressup");s_oStage.removeChild(m)};this.setVisible=function(a){m.visible=a};this.enable=function(){h=!1;p.filters=[];p.cache(0,0,k,n)};this.disable=function(){h=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100);p.filters=[new createjs.ColorMatrixFilter(a)];p.cache(0,0,k,n)};this._initListener=function(){oParent=this;m.on("mousedown",this.buttonDown);m.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,e){c[a]=b;u[a]=e};this.buttonRelease=function(){h||(!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||createjs.Sound.play("press_but"),m.scaleX=1,m.scaleY=1,c[ON_MOUSE_UP]&&c[ON_MOUSE_UP].call(u[ON_MOUSE_UP]))};this.buttonDown=function(){h||(m.scaleX=.9,m.scaleY=.9,c[ON_MOUSE_DOWN]&&c[ON_MOUSE_DOWN].call(u[ON_MOUSE_DOWN]))};this.setPosition=function(a,b){m.x=a;m.y=b};this.changeText=function(a){q.text=a};this.setX=function(a){m.x=a};this.setY=function(a){m.y=a};this.getButtonImage=function(){return m};this.getX=function(){return m.x};this.getY=function(){return m.y};this._init(a,d,
f,b,g,e,l);return this}
function CGfxButton(a,d,f,b){var g,e,l,h,k,n,c;this._init=function(a,b,d,f){g=!1;h=[];k=[];c=createBitmap(d);c.x=a;c.y=b;e=d.width;l=d.height;c.regX=d.width/2;c.regY=d.height/2;c.cursor="pointer";!1!==f&&s_oStage.addChild(c);this._initListener()};this.unload=function(){c.off("mousedown",this.buttonDown);c.off("pressup",this.buttonRelease);s_oStage.removeChild(c)};this.setVisible=function(a){c.visible=a};this.enable=function(){g=!1;c.filters=[];c.cache(0,0,e,l)};this.disable=function(){g=!0;var a=
(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);c.filters=[new createjs.ColorMatrixFilter(a)];c.cache(0,0,e,l)};this._initListener=function(){c.on("mousedown",this.buttonDown);c.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){h[a]=b;k[a]=c};this.addEventListenerWithParams=function(a,b,c,e){h[a]=b;k[a]=c;n=e};this.buttonRelease=function(){g||(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but"),c.scaleX=1,c.scaleY=1,h[ON_MOUSE_UP]&&
h[ON_MOUSE_UP].call(k[ON_MOUSE_UP],n))};this.buttonDown=function(){g||(c.scaleX=.9,c.scaleY=.9,h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN],n))};this.setPosition=function(a,b){c.x=a;c.y=b};this.setX=function(a){c.x=a};this.setY=function(a){c.y=a};this.getButtonImage=function(){return c};this.getX=function(){return c.x};this.getY=function(){return c.y};this.getSprite=function(){return c};this._init(a,d,f,b);return this}
function CToggle(a,d,f,b,g){var e,l,h,k,n,c,u;this._init=function(a,b,c,d,f){u=void 0!==f?f:s_oStage;l=[];h=[];f=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});e=d;k=createSprite(f,"state_"+e,c.width/2/2,c.height/2,c.width/2,c.height);k.x=a;k.y=b;k.stop();s_bMobile||(k.cursor="pointer");u.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown",n);k.off("pressup",c);u.removeChild(k)};
this._initListener=function(){n=k.on("mousedown",this.buttonDown);c=k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){l[a]=b;h[a]=c};this.setCursorType=function(a){k.cursor=a};this.setActive=function(a){e=a;k.gotoAndStop("state_"+e)};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but");e=!e;k.gotoAndStop("state_"+e);l[ON_MOUSE_UP]&&l[ON_MOUSE_UP].call(h[ON_MOUSE_UP],e)};this.buttonDown=function(){k.scaleX=
.9;k.scaleY=.9;l[ON_MOUSE_DOWN]&&l[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN])};this.setPosition=function(a,b){k.x=a;k.y=b};this._init(a,d,f,b,g)}
function CBetBut(a,d,f){var b,g,e,l=[],h;this._init=function(a,d,c){b=!1;g=[];e=[];c=s_oSpriteLibrary.getSprite("bet_but");var f=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:0,regY:0},animations:{on:[0,1],off:[1,2]}});h=createSprite(f,"on",0,0,c.width/2,c.height);h.stop();h.x=a;h.y=d;h.regX=c.width/2;h.regY=c.height/2;h.cursor="pointer";s_oStage.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",this.buttonRelease);
s_oStage.removeChild(h)};this.disable=function(a){b=a};this.setVisible=function(a){h.visible=a};this.setOn=function(){h.gotoAndStop("on")};this.setOff=function(){h.gotoAndStop("off")};this._initListener=function(){h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){g[a]=b;e[a]=c};this.addEventListenerWithParams=function(a,b,c,d){g[a]=b;e[a]=c;l=d};this.buttonRelease=function(){g[ON_MOUSE_UP]&&!1===b&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||
createjs.Sound.play("press_but"),g[ON_MOUSE_UP].call(e[ON_MOUSE_UP],l))};this.buttonDown=function(){g[ON_MOUSE_DOWN]&&!1===b&&g[ON_MOUSE_DOWN].call(e[ON_MOUSE_DOWN],l)};this.setPosition=function(a,b){h.x=a;h.y=b};this.setX=function(a){h.x=a};this.setY=function(a){h.y=a};this.getButtonImage=function(){return h};this.getX=function(){return h.x};this.getY=function(){return h.y};this._init(a,d,f)}
function CMenu(){var a,d,f,b,g,e,l,h=null,k=null,n,c,u,m,q;this._init=function(){n=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(n);var p=s_oSpriteLibrary.getSprite("but_play_bg");c=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-80,p,TEXT_PLAY,FONT_GAME,"#ffde00",58);c.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)p=s_oSpriteLibrary.getSprite("audio_icon"),g=CANVAS_WIDTH-p.width/4-10,e=p.height/2+10,m=new CToggle(g,e,p,
s_bAudioActive,s_oStage),m.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),null===s_oSoundTrack?s_oSoundTrack=createjs.Sound.play("soundtrack",{volume:SOUNDTRACK_VOLUME,loop:-1}):s_oSoundTrack.volume=1;SHOW_CREDITS?(p=s_oSpriteLibrary.getSprite("but_credits"),a=p.height/2+10,d=p.height/2+10,u=new CGfxButton(a,d,p,s_oStage),u.addEventListener(ON_MOUSE_UP,this._onButCreditsRelease,this),f=a+p.width+10,b=d):(f=p.height/2+10,b=p.height/2+10);var p=window.document,v=p.documentElement;h=v.requestFullscreen||
v.mozRequestFullScreen||v.webkitRequestFullScreen||v.msRequestFullscreen;k=p.exitFullscreen||p.mozCancelFullScreen||p.webkitExitFullscreen||p.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(h=!1);h&&!1===inIframe()&&(p=s_oSpriteLibrary.getSprite("but_fullscreen"),l=new CToggle(f,b,p,s_bFullscreen,s_oStage),l.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));q=new createjs.Shape;q.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(q);createjs.Tween.get(q).to({alpha:0},
600).call(function(){q.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(c,n){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||m.setPosition(g-c,n+e);h&&!1===inIframe()&&l.setPosition(f+c,b+n);SHOW_CREDITS&&u.setPosition(a+c,d+n)};this.unload=function(){c.unload();c=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)m.unload(),m=null;SHOW_CREDITS&&u.unload();h&&!1===inIframe()&&l.unload();s_oStage.removeAllChildren();s_oMenu=null};this._onButPlayRelease=function(){this.unload();
!isIOS()||null!==s_oSoundTrack||!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||(s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1}));s_oMain.gotoGame();$(s_oMain).trigger("start_session")};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButCreditsRelease=function(){new CCreditsPanel};this._onFullscreenRelease=function(){s_bFullscreen?(k.call(window.document),s_bFullscreen=!1):(h.call(window.document.documentElement),s_bFullscreen=!0);
sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a){var d=!1,f,b,g=!0,e,l,h,k,n,c,u,m,q,p,v,z=0,y,x,D,w,C,A,E,B,F,I,H,r,N,J,K,L,t,G=null,M;this._init=function(){e=GAME_STATE_IDLE;f=!0;D=v=k=l=0;E=[0,1,2,3,4];h=E[0];n=NUM_PAYLINES;p=TOTAL_MONEY;m=MIN_BET;q=m*n;B=[];for(var a=0;a<NUM_ROWS;a++){B[a]=[];for(var b=0;b<NUM_REELS;b++)B[a][b]=0}s_oTweenController=new CTweenController;K=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(K);this._initReels();L=createBitmap(s_oSpriteLibrary.getSprite("mask_slot"));s_oStage.addChild(L);
this._initStaticSymbols();this._initHitAreaColumn();t=new CInterface(m,q,p);M=new CBonusPanel;G=new CPayTablePanel;p<q&&t.disableSpin();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack.volume=.4;d=!0};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)createjs.Sound.stop(),s_oSoundTrack=null;s_oStage.removeChild(K);s_oStage.removeChild(L);t.unload();G.unload();for(var a=0;a<w.length;a++)w[a].unload();for(a=0;a<NUM_ROWS;a++)for(var b=0;b<NUM_REELS;b++)C[a][b].unload();M.unload()};
this._initReels=function(){var a=REEL_OFFSET_X,b=REEL_OFFSET_Y,c=0;w=[];for(var e=0;e<NUM_REELS;e++)w[e]=new CReelColumn(e,a,b,c),w[e+NUM_REELS]=new CReelColumn(e+NUM_REELS,a,b+SYMBOL_SIZE*NUM_ROWS,c),a+=SYMBOL_SIZE+SPACE_BETWEEN_SYMBOLS,c+=REEL_DELAY};this._initStaticSymbols=function(){var a=REEL_OFFSET_X,b=REEL_OFFSET_Y;C=[];for(var c=0;c<NUM_ROWS;c++){C[c]=[];for(var e=0;e<NUM_REELS;e++){var d=new CStaticSymbolCell(c,e,a,b);C[c][e]=d;a+=SYMBOL_SIZE+SPACE_BETWEEN_SYMBOLS}a=REEL_OFFSET_X;b+=SYMBOL_SIZE}};
this._initHitAreaColumn=function(){r=[];H=[];for(var a=376,b=116,c=0;c<NUM_REELS;c++){var e=createBitmap(s_oSpriteLibrary.getSprite("hold_col"));e.x=a;e.y=b;e.visible=!1;s_oStage.addChild(e);a+=150;H.push(e);r[c]=!1}F=[];I=[];for(var a=381,b=108,c=s_oSpriteLibrary.getSprite("hit_area_col"),e=0;e<NUM_REELS;e++){var d=new createjs.Text(TEXT_HOLD,"30px "+FONT_GAME,"#ffffff");d.visible=!1;d.x=a+c.width/2;d.y=b+c.height-20;d.shadow=new createjs.Shadow("#000",1,1,2);d.textAlign="center";s_oStage.addChild(d);
F[e]=d;d=new CGfxButton(a+c.width/2,b+c.height/2,c);d.setVisible(!1);d.addEventListenerWithParams(ON_MOUSE_UP,this._onHitAreaCol,this,{index:e});a+=150;I.push(d)}};this.generateFinalSymbols=function(){for(var a=0;a<NUM_ROWS;a++)for(var b=0;b<NUM_REELS;b++)!1===w[b].isHold()&&(B[a][b]=s_aRandSymbols[Math.floor(Math.random()*s_aRandSymbols.length)]);a=this._checkForCombos();this._checkForBonus();return a};this._checkForCombos=function(){A=[];for(var a=y=0;a<n;a++){var b=s_aPaylineCombo[a],c=[],e=B[b[0].row][b[0].col];
if(e!==BONUS_SYMBOL){var d=1,f=1;for(c.push({row:b[0].row,col:b[0].col,value:B[b[0].row][b[0].col]});e===WILD_SYMBOL&&f<NUM_REELS;)d++,e=B[b[f].row][b[f].col],c.push({row:b[f].row,col:b[f].col,value:B[b[f].row][b[f].col]}),f++;for(;f<b.length;f++)if(B[b[f].row][b[f].col]===e||B[b[f].row][b[f].col]===WILD_SYMBOL){if(B[b[f].row][b[f].col]===BONUS_SYMBOL)break;d++;c.push({row:b[f].row,col:b[f].col,value:B[b[f].row][b[f].col]})}else break;e!==BONUS_SYMBOL&&0<s_aSymbolWin[e-1][d-1]&&(y+=s_aSymbolWin[e-
1][d-1],A.push({line:a+1,amount:s_aSymbolWin[e-1][d-1],num_win:d,value:e,list:c}))}}return y>q?!0:!1};this._checkForBonus=function(){b=!1;z=0;for(var a=[],c=0;c<NUM_ROWS;c++)for(var e=0;e<NUM_REELS;e++)B[c][e]===BONUS_SYMBOL&&(a.push({row:c,col:e,value:B[c][e]}),z++);z>=NUM_SYMBOLS_FOR_BONUS&&(A.push({line:-1,amount:0,num_win:z,value:BONUS_SYMBOL,list:a}),5<z&&(z=5),b=!0)};this._generateRandSymbols=function(){for(var a=[],b=0;b<NUM_ROWS;b++)a[b]=s_aRandSymbols[Math.floor(Math.random()*s_aRandSymbols.length)];
return a};this.reelArrived=function(a,b){if(l>MIN_REEL_LOOPS)if(h===b){if(!1===w[a].isReadyToStop()){var c=a;a<NUM_REELS?(c+=NUM_REELS,w[c].setReadyToStop(),w[a].restart([B[0][a],B[1][a],B[2][a]],!0)):(c-=NUM_REELS,w[c].setReadyToStop(),w[a].restart([B[0][c],B[1][c],B[2][c]],!0))}}else w[a].restart(this._generateRandSymbols(),!1);else w[a].restart(this._generateRandSymbols(),!1),0===a&&l++};this.increaseReelLoops=function(){l+=2};this.stopNextReel=function(){k++;0===k%2&&(!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||createjs.Sound.play("reel_stop",{volume:.3}),h=E[k/2],k===2*NUM_REELS&&this._endReelAnimation())};this._endReelAnimation=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||N.stop();k=l=0;h=E[0];for(var a=0;a<NUM_REELS;a++)r[a]=!1,H[a].visible=!1,w[a].setHold(!1),w[a+NUM_REELS].setHold(!1);v=0;if(0<A.length){for(var d=0;d<A.length;d++){G.highlightCombo(A[d].value,A[d].num_win);-1!==A[d].line&&t.showLine(A[d].line);for(var n=A[d].list,a=0;a<n.length;a++)C[n[a].row][n[a].col].show(n[a].value)}y*=
m;p+=y;SLOT_CASH-=y;0<y&&(t.refreshMoney(p),t.refreshWinText(y));c=0;e=GAME_STATE_SHOW_ALL_WIN;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)J=createjs.Sound.play("win");f=!0;!1===b&&(t.disableBetBut(!1),t.enableGuiButtons())}else f?(this.enableColumnHitArea(),f=!1,t.enableSpin(),t.disableMaxBet()):(t.disableBetBut(!1),t.enableGuiButtons(),f=!0),t.refreshWinText(0),e=GAME_STATE_IDLE;p<q&&t.disableSpin();D++;D===x&&(D=0,$(s_oMain).trigger("show_interlevel_ad"));$(s_oMain).trigger("save_score",p)};this.hidePayTable=
function(){G.hide()};this._showWin=function(){var a;if(0<u){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||J.stop();-1!==A[u-1].line&&(a=A[u-1].line,t.hideLine(a));a=A[u-1].list;for(var b=0;b<a.length;b++)C[a[b].row][a[b].col].stopAnim()}u===A.length&&(u=0);-1!==A[u].line&&(a=A[u].line,t.showLine(a));a=A[u].list;for(b=0;b<a.length;b++)C[a[b].row][a[b].col].show(a[b].value);u++};this._hideAllWins=function(){for(var a=0;a<A.length;a++)for(var d=A[a].list,f=0;f<d.length;f++)C[d[f].row][d[f].col].stopAnim();
t.hideAllLines();u=c=0;c=TIME_SHOW_WIN;e=GAME_STATE_SHOW_WIN;b&&M.show(z,m)};this.enableColumnHitArea=function(){for(var a=0;a<NUM_REELS;a++)F[a].visible=!0,I[a].setVisible(!0)};this.disableColumnHitArea=function(){for(var a=0;a<NUM_REELS;a++)F[a].visible=!1,I[a].setVisible(!1)};this.activateLines=function(a){n=a;this.removeWinShowing();q=a=m*n;t.refreshTotalBet(q);t.refreshNumLines(n);a>p?t.disableSpin():t.enableSpin()};this.addLine=function(){n===NUM_PAYLINES?n=1:n++;var a=m*n;q=a;t.refreshTotalBet(q);
t.refreshNumLines(n);a>p?t.disableSpin():t.enableSpin()};this.changeCoinBet=function(){var a=Math.floor(100*(m+.05))/100;a>MAX_BET?(m=MIN_BET,q=m*n,t.refreshBet(m),t.refreshTotalBet(q),a=q):(a*=n,m+=.05,m=Math.floor(100*m)/100,q=a,t.refreshBet(m),t.refreshTotalBet(q));a>p?t.disableSpin():t.enableSpin()};this.onMaxBet=function(){var a=MAX_BET;n=NUM_PAYLINES;a*=n;m=MAX_BET;q=a;t.refreshBet(m);t.refreshTotalBet(q);t.refreshNumLines(n);a>p?t.disableSpin():(t.enableSpin(),this.onSpin())};this._onHitAreaCol=
function(a){a=a.index;!0===r[a]?(r[a]=!1,H[a].visible=!1,F[a].visible=!0,v--,w[a].setHold(!1),w[a+NUM_REELS].setHold(!1)):v<MAX_NUM_HOLD&&(r[a]=!0,v++,H[a].visible=!0,F[a].visible=!1,w[a].setHold(!0),w[a+NUM_REELS].setHold(!0),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_hold"))};this.removeWinShowing=function(){G.resetHighlightCombo();t.resetWin();for(var a=0;a<NUM_ROWS;a++)for(var b=0;b<NUM_REELS;b++)C[a][b].hide();for(a=0;a<w.length;a++)w[a].activate();e=GAME_STATE_IDLE};
this.endBonus=function(a){a*=m;p+=a;t.refreshMoney(p);SLOT_CASH-=a;t.disableBetBut(!1);t.enableGuiButtons()};this.onSpin=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)J&&J.stop(),N=createjs.Sound.play("reels",{volume:.3});this.disableColumnHitArea();t.disableBetBut(!0);this.removeWinShowing();MIN_WIN=s_aSymbolWin[0][s_aSymbolWin[0].length-1];for(var a=0;a<s_aSymbolWin.length;a++)for(var c=s_aSymbolWin[a],d=0;d<c.length;d++)0!==c[d]&&c[d]<MIN_WIN&&(MIN_WIN=c[d]);MIN_WIN*=m;f&&(p-=q,t.refreshMoney(p),
SLOT_CASH+=q,$(s_oMain).trigger("bet_placed",{bet:m,tot_bet:q}));if(!g&&w[0].visible&&w[1].visible&&this._checkForCombos())this._assignWin();else if(SLOT_CASH<MIN_WIN){do a=this.generateFinalSymbols();while(!0===a||b)}else if(Math.floor(100*Math.random())>WIN_OCCURRENCE){do a=this.generateFinalSymbols();while(!0===a||b)}else this._assignWin();t.hideAllLines();t.disableGuiButtons();g=!1;e=GAME_STATE_SPINNING};this._assignWin=function(){if(SLOT_CASH<BONUS_PRIZE[0][0]*m){var a=0;do{var c=this.generateFinalSymbols();
a++}while((!1===c||y*m>SLOT_CASH||b)&&1E4>=a)}else if(Math.floor(100*Math.random())>=BONUS_OCCURRENCE){a=0;do c=this.generateFinalSymbols(),a++;while((!1===c||y*m>SLOT_CASH||b)&&1E4>=a)}else{a=0;do{var c=this.generateFinalSymbols(),e=0;b&&(e=z-3);a++}while((!1===c||y*m+BONUS_PRIZE[e][0]*m>SLOT_CASH||!1===b)&&1E4>=a)}if(1E4<a){do c=this.generateFinalSymbols();while(!0===c||b)}};this.onInfoClicked=function(){e!==GAME_STATE_SPINNING&&(G.isVisible()?G.hide():G.show())};this.onExit=function(){this.unload();
s_oMain.gotoMenu();$(s_oMain).trigger("end_session");$(s_oMain).trigger("share_event",{img:"200x200.jpg",title:TEXT_CONGRATULATIONS,msg:TEXT_MSG_SHARE1+p+TEXT_MSG_SHARE2,msg_share:TEXT_MSG_SHARING1+p+TEXT_MSG_SHARING2})};this.getState=function(){return e};this.update=function(){if(!1!==d)switch(e){case GAME_STATE_SPINNING:for(var a=0;a<w.length;a++)w[a].update(h);break;case GAME_STATE_SHOW_ALL_WIN:c+=s_iTimeElaps;c>TIME_SHOW_ALL_WINS&&this._hideAllWins();break;case GAME_STATE_SHOW_WIN:c+=s_iTimeElaps,
c>TIME_SHOW_WIN&&(c=0,this._showWin())}};s_oGame=this;WIN_OCCURRENCE=a.win_occurrence;SLOT_CASH=a.slot_cash;BONUS_OCCURRENCE=a.bonus_occurrence;MIN_REEL_LOOPS=a.min_reel_loop;REEL_DELAY=a.reel_delay;TIME_SHOW_WIN=a.time_show_win;TIME_SHOW_ALL_WINS=a.time_show_all_wins;TOTAL_MONEY=a.money;MIN_BET=a.min_bet;MAX_BET=a.max_bet;MAX_NUM_HOLD=a.max_hold;BONUS_PRIZE[0]=a.bonus_prize_for_3_symbol;BONUS_PRIZE[1]=a.bonus_prize_for_4_symbol;BONUS_PRIZE[2]=a.bonus_prize_for_5_symbol;PERC_WIN_PRIZE_1=a.perc_win_prize_1;
PERC_WIN_PRIZE_2=a.perc_win_prize_2;PERC_WIN_PRIZE_3=a.perc_win_prize_3;ENABLE_FULLSCREEN=a.fullscreen;x=a.num_spin_ads_showing;new CSlotSettings;this._init()}var s_oGame,s_oTweenController;
function CReelColumn(a,d,f,b){var g,e,l,h,k,n,c,u,m,q,p,v,z,y,x;this._init=function(a,b,d,f){h=l=e=g=!1;u=0;k=a;c=f;n=k<NUM_REELS?k:k-NUM_REELS;q=0;p=MAX_FRAMES_REEL_EASE;m=REEL_STATE_START;v=d;z=v+SYMBOL_SIZE*NUM_ROWS;this.initContainer(b,d)};this.initContainer=function(a,b){x=new createjs.Container;x.x=a;x.y=b;var c=0;y=[];for(var e=0;e<NUM_ROWS;e++){var d=createSprite(s_aSymbolData[s_aRandSymbols[Math.floor(Math.random()*s_aRandSymbols.length)]],"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE);d.stop();d.x=
0;d.y=c;x.addChild(d);y[e]=d;c+=SYMBOL_SIZE}s_oStage.addChild(x)};this.unload=function(){s_oStage.removeChild(x)};this.activate=function(){v=x.y;z=v+SYMBOL_SIZE*NUM_ROWS;g=!0};this._setSymbol=function(a){x.removeAllChildren();for(var b=0,c=0;c<a.length;c++){var d=new createSprite(s_aSymbolData[a[c]],"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE);d.stop();d.x=0;d.y=b;x.addChild(d);y[c]=d;b+=SYMBOL_SIZE}};this.setHold=function(a){h=a};this.restart=function(a,b){x.y=v=REEL_START_Y;z=v+SYMBOL_SIZE*NUM_ROWS;this._setSymbol(a);
if(e=b){q=0;p=MAX_FRAMES_REEL_EASE;m=REEL_STATE_STOP;for(var c=0;c<NUM_ROWS;c++)y[c].gotoAndStop("static");l=!0}else for(c=0;c<NUM_ROWS;c++)y[c].gotoAndStop("moving")};this.setReadyToStop=function(){q=0;p=MAX_FRAMES_REEL_EASE;m=REEL_STATE_STOP};this.isReadyToStop=function(){return e};this.isHold=function(){return h};this._updateStart=function(){0===q&&k<NUM_REELS&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("start_reel",{volume:.3}));q++;q>p&&(q=0,p/=2,m++,v=x.y,z=v+SYMBOL_SIZE*
NUM_ROWS);var a=s_oTweenController.easeInBack(q,0,1,p),a=s_oTweenController.tweenValue(v,z,a);x.y=a};this._updateMoving=function(){q++;q>p&&(q=0,v=x.y,z=v+SYMBOL_SIZE*NUM_ROWS);var a=s_oTweenController.easeLinear(q,0,1,p),a=s_oTweenController.tweenValue(v,z,a);x.y=a};this._updateStopping=function(){q++;if(q>=p)g=!1,q=0,p=MAX_FRAMES_REEL_EASE,m=REEL_STATE_START,u=0,e=!1,l&&(l=!1,x.y=REEL_OFFSET_Y),s_oGame.stopNextReel();else{var a=s_oTweenController.easeOutCubic(q,0,1,p),a=s_oTweenController.tweenValue(v,
z,a);x.y=a}};this.update=function(a){if(!1!==g&&(u++,u>c))if(h)a===k&&(g=!1,s_oGame.stopNextReel(),s_oGame.stopNextReel(),0===k&&s_oGame.increaseReelLoops());else switch(!1===e&&x.y>REEL_ARRIVAL_Y&&s_oGame.reelArrived(k,n),m){case REEL_STATE_START:this._updateStart();break;case REEL_STATE_MOVING:this._updateMoving();break;case REEL_STATE_STOP:this._updateStopping()}};this._init(a,d,f,b)}
function CInterface(a,d,f){var b,g,e,l,h,k,n,c,u,m,q,p,v,z,y,x,D,w,C,A,E=null,B=null;this._init=function(a,d,f){var r=s_oSpriteLibrary.getSprite("but_exit");e=CANVAS_WIDTH-r.width/2-10;l=r.height/2+10;u=new CGfxButton(e,l,r,!0);u.addEventListener(ON_MOUSE_UP,this._onExit,this);!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(h=u.getX()-r.width,k=r.height/2+10,v=new CToggle(h,k,s_oSpriteLibrary.getSprite("audio_icon"),s_bAudioActive,s_oStage),v.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),b=h-
r.width):b=e-r.width;g=r.height/2+10;var r=window.document,F=r.documentElement;E=F.requestFullscreen||F.mozRequestFullScreen||F.webkitRequestFullScreen||F.msRequestFullscreen;B=r.exitFullscreen||r.mozCancelFullScreen||r.webkitExitFullscreen||r.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(E=!1);E&&!1===inIframe()&&(r=s_oSpriteLibrary.getSprite("but_fullscreen"),A=new CToggle(b,g,r,s_bFullscreen,s_oStage),A.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));r=s_oSpriteLibrary.getSprite("spin_but");
m=new CTextButton(1094+r.width/2,CANVAS_HEIGHT-r.height/2-4,r,TEXT_WIN+"\n0.00",FONT_GAME,"#ffde00",26);m.addEventListener(ON_MOUSE_UP,this._onSpin,this);r=s_oSpriteLibrary.getSprite("info_but");q=new CTextButton(320+r.width/2,CANVAS_HEIGHT-r.height/2-4,r,TEXT_INFO,FONT_GAME,"#ffffff",32);q.addEventListener(ON_MOUSE_UP,this._onInfo,this);r=s_oSpriteLibrary.getSprite("but_lines_bg");p=new CTextButton(490+r.width/2,CANVAS_HEIGHT-r.height/2-4,r,TEXT_LINES,FONT_GAME,"#ffffff",32);p.addEventListener(ON_MOUSE_UP,
this._onAddLine,this);r=s_oSpriteLibrary.getSprite("coin_but");z=new CTextButton(678+r.width/2,CANVAS_HEIGHT-r.height/2-4,r,TEXT_COIN,FONT_GAME,"#ffffff",32);z.addEventListener(ON_MOUSE_UP,this._onBet,this);r=s_oSpriteLibrary.getSprite("but_maxbet_bg");y=new CTextButton(866+r.width/2,CANVAS_HEIGHT-r.height/2-4,r,TEXT_MAX_BET,FONT_GAME,"#ffffff",32);y.addEventListener(ON_MOUSE_UP,this._onMaxBet,this);D=new createjs.Text(TEXT_MONEY+"\n"+f.toFixed(2)+TEXT_CURRENCY,"34px "+FONT_GAME,"#ffde00");D.x=450;
D.y=46;D.textBaseline="alphabetic";D.lineHeight=28;D.textAlign="center";s_oStage.addChild(D);C=new createjs.Text(NUM_PAYLINES,"24px "+FONT_GAME,"#ffde00");C.x=584;C.y=CANVAS_HEIGHT-77;C.shadow=new createjs.Shadow("#000",2,2,2);C.textAlign="center";C.textBaseline="alphabetic";s_oStage.addChild(C);x=new createjs.Text(a.toFixed(2),"24px "+FONT_GAME,"#ffde00");x.x=776;x.y=CANVAS_HEIGHT-77;x.shadow=new createjs.Shadow("#000",2,2,2);x.textAlign="center";x.textBaseline="alphabetic";s_oStage.addChild(x);
w=new createjs.Text(TEXT_BET+": "+d.toFixed(2),"24px "+FONT_GAME,"#ffde00");w.x=980;w.y=CANVAS_HEIGHT-77;w.shadow=new createjs.Shadow("#000",2,2,2);w.textAlign="center";w.textBaseline="alphabetic";s_oStage.addChild(w);r=s_oSpriteLibrary.getSprite("bet_but");n=[];a=new CBetBut(334+r.width/2,282+r.height/2,r,!0);a.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,1);n[0]=a;a=new CBetBut(334+r.width/2,180+r.height/2,r,!0);a.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,
this,2);n[1]=a;a=new CBetBut(334+r.width/2,432+r.height/2,r,!0);a.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,3);n[2]=a;a=new CBetBut(334+r.width/2,114+r.height/2,r,!0);a.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,4);n[3]=a;a=new CBetBut(334+r.width/2,502+r.height/2,r,!0);a.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,5);n[4]=a;c=[];for(a=0;a<NUM_PAYLINES;a++)d=new createjs.Bitmap(s_oSpriteLibrary.getSprite("payline_"+(a+1))),d.visible=
!1,s_oStage.addChild(d),c[a]=d;this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){u.unload();u=null;m.unload();m=null;q.unload();q=null;p.unload();p=null;z.unload();z=null;y.unload();y=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)v.unload(),v=null;E&&!1===inIframe()&&A.unload();for(var a=0;a<NUM_PAYLINES;a++)n[a].unload();s_oStage.removeAllChildren();s_oInterface=null};this.refreshButtonPos=function(a,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||v.setPosition(h-a,c+k);E&&!1===
inIframe()&&A.setPosition(b-a,g+c);u.setPosition(e-a,c+l)};this.refreshMoney=function(a){D.text=TEXT_MONEY+"\n"+a.toFixed(2)+TEXT_CURRENCY};this.refreshBet=function(a){x.text=a.toFixed(2)};this.refreshTotalBet=function(a){w.text=TEXT_BET+": "+a.toFixed(2)};this.refreshNumLines=function(a){C.text=a;for(var b=0;b<NUM_PAYLINES;b++)b<a?(n[b].setOn(),c[b].visible=!0):n[b].setOff();setTimeout(function(){for(var a=0;a<NUM_PAYLINES;a++)c[a].visible=!1},1E3)};this.resetWin=function(){m.changeText("")};this.refreshWinText=
function(a){m.changeText(TEXT_WIN+"\n"+a.toFixed(2))};this.showLine=function(a){c[a-1].visible=!0};this.hideLine=function(a){c[a-1].visible=!1};this.hideAllLines=function(){for(var a=0;a<NUM_PAYLINES;a++)c[a].visible=!1};this.disableBetBut=function(a){for(var b=0;b<NUM_PAYLINES;b++)n[b].disable(a)};this.enableGuiButtons=function(){m.enable();y.enable();z.enable();p.enable();q.enable()};this.enableSpin=function(){m.enable();y.enable()};this.disableSpin=function(){m.disable();y.disable()};this.enableMaxBet=
function(){y.enable()};this.disableMaxBet=function(){y.disable()};this.disableGuiButtons=function(){m.disable();y.disable();z.disable();p.disable();q.disable()};this._onBetLineClicked=function(a){this.refreshNumLines(a);s_oGame.activateLines(a)};this._onExit=function(){s_oGame.onExit()};this._onSpin=function(){s_oGame.onSpin()};this._onAddLine=function(){s_oGame.addLine()};this._onInfo=function(){s_oGame.onInfoClicked()};this._onBet=function(){s_oGame.changeCoinBet()};this._onMaxBet=function(){s_oGame.onMaxBet()};
this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onFullscreenRelease=function(){s_bFullscreen?(B.call(window.document),s_bFullscreen=!1):(E.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};s_oInterface=this;this._init(a,d,f);return this}var s_oInterface=null;
function CPayTablePanel(){var a,d,f,b,g,e;this._init=function(){e=new createjs.Container;g=createBitmap(s_oSpriteLibrary.getSprite("paytable"));e.addChild(g);this._createPayouts();f=new createjs.Text(TEXT_HELP_WILD,"21px "+FONT_GAME,"#ffff00");f.textAlign="center";f.lineWidth=220;f.lineHeight=22;f.x=635;f.y=290;e.addChild(f);b=new createjs.Text(TEXT_HELP_BONUS,"21px "+FONT_GAME,"#ffff00");b.textAlign="center";b.lineHeight=22;b.lineWidth=210;b.x=976;b.y=294;e.addChild(b);e.visible=!1;s_oStage.addChild(e);
var a=this;e.on("pressup",function(){a._onExit()})};this.unload=function(){var b=this;e.off("pressup",function(){b._onExit()});s_oStage.removeChild(e);for(var f=0;f<a.length;f++)e.removeChild(a[f]);for(f=0;f<d.length;f++)e.removeChild(d[f])};this._createPayouts=function(){a=[];d=[];for(var b=[{x:446,y:106},{x:654,y:106},{x:860,y:106},{x:1070,y:106},{x:446,y:195},{x:654,y:195},{x:860,y:195},{x:1070,y:195}],f=0,g=0;g<s_aSymbolWin.length;g++){for(var n=[],c=0;c<s_aSymbolWin[g].length;c++)n[c]=s_aSymbolWin[g][c];
do c=n.indexOf(0),-1!==c&&n.splice(c,1);while(-1!==c);c=n.length;if(0!==c){var u=30;4===c&&(u=22);var m=b[f].y;a[g]=[];d[g]=[];for(var q=0;q<c;q++){var p=new createjs.Text("X"+(5-q),"25px "+FONT_GAME,"#ffffff");p.textAlign="center";p.x=b[f].x;p.y=m;p.textBaseline="alphabetic";e.addChild(p);a[g][q]=p;var v=new createjs.Text(n[c-q-1],"25px "+FONT_GAME,"#ffff00");v.textAlign="center";v.x=p.x+50;v.y=p.y;v.textBaseline="alphabetic";e.addChild(v);d[g][q]=v;m+=u}f++}}};this.show=function(){e.visible=!0};
this.hide=function(){e.visible=!1};this.resetHighlightCombo=function(){for(var b=0;b<a.length;b++)for(var e=0;e<a[b].length;e++)a[b][e].color="#ffffff",d[b][e].color="#ffff00",createjs.Tween.removeTweens(d[b][e]),d[b][e].alpha=1};this.highlightCombo=function(a,b){a!==BONUS_SYMBOL&&(d[a-1][NUM_REELS-b].color="#ff0000",this.tweenAlpha(d[a-1][NUM_REELS-b],0))};this.tweenAlpha=function(a,b){var d=this;createjs.Tween.get(a).to({alpha:b},200).call(function(){1===b?d.tweenAlpha(a,0):d.tweenAlpha(a,1)})};
this._onExit=function(){s_oGame.hidePayTable()};this.isVisible=function(){return e.visible};this._init()}
function CStaticSymbolCell(a,d,f,b){var g=-1,e,l,h,k;this._init=function(a,b,d,e){k=new createjs.Container;k.visible=!1;l=[];for(a=0;a<NUM_SYMBOLS;a++)b=createSprite(s_aSymbolAnims[a],"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE),b.stop(),b.x=d,b.y=e,b.on("animationend",this._onAnimEnded,null,!1,{index:a}),k.addChild(b),l[a]=b,l[a].visible=!1;a={framerate:60,images:[s_oSpriteLibrary.getSprite("win_frame_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,
19]}};a=new createjs.SpriteSheet(a);h=new createSprite(a,"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE);h.stop();h.x=d;h.y=e;k.addChild(h);s_oStage.addChild(k)};this.unload=function(){s_oStage.removeChild(k)};this.hide=function(){-1<g&&(h.gotoAndStop("static"),h.visible=!1,l[g].gotoAndPlay("static"),k.visible=!1)};this.show=function(a){h.gotoAndPlay("anim");h.visible=!0;for(var b=0;b<NUM_SYMBOLS;b++)l[b].visible=b+1===a?!0:!1;l[a-1].gotoAndPlay("anim");g=a-1;e=l[a-1].spriteSheet.getNumFrames();k.visible=!0};
this._onAnimEnded=function(a,b){l[b.index].currentFrame!==e&&(l[b.index].stop(),setTimeout(function(){l[b.index].gotoAndPlay(1)},100))};this.stopAnim=function(){l[g].gotoAndStop("static");l[g].visible=!1;h.gotoAndStop("static");h.visible=!1};this._init(a,d,f,b)}
function CTweenController(){this.tweenValue=function(a,d,f){return a+f*(d-a)};this.easeLinear=function(a,d,f,b){return f*a/b+d};this.easeInCubic=function(a,d,f,b){b=(a/=b)*a*a;return d+f*b};this.easeBackInQuart=function(a,d,f,b){b=(a/=b)*a;return d+f*(2*b*b+2*b*a+-3*b)};this.easeInBack=function(a,d,f,b){return f*(a/=b)*a*(2.70158*a-1.70158)+d};this.easeOutCubic=function(a,d,f,b){return f*((a=a/b-1)*a*a+1)+d}}
function CBonusPanel(){var a,d,f,b,g,e,l,h,k;this._init=function(){k=new createjs.Container;s_oStage.addChild(k);var a=createBitmap(s_oSpriteLibrary.getSprite("bonus_bg"));k.alpha=0;k.visible=!1;k.addChild(a);a={framerate:6,images:[s_oSpriteLibrary.getSprite("bonus_item")],frames:{width:BONUS_ITEM_WIDTH,height:BONUS_ITEM_HEIGHT},animations:{idle:[0],item_clicked:[1,14,"idle"]}};a=new createjs.SpriteSheet(a);b=[];for(var c=[{x:253,y:30},{x:577,y:118},{x:946,y:19},{x:262,y:305},{x:927,y:305}],d=0;5>
d;d++){var f=createSprite(a,"idle",0,0,BONUS_ITEM_WIDTH,BONUS_ITEM_HEIGHT);f.on("click",this._onBonusItemReleased,this,!1,d);f.x=c[d].x;f.y=c[d].y;f.visible=!1;k.addChild(f);b[d]=f}a=s_oSpriteLibrary.getSprite("bonus_prize");e=[];l=[];e[0]=createBitmap(a);e[0].x=300;e[0].y=CANVAS_HEIGHT-90;k.addChild(e[0]);c=new createjs.Text("100","44px "+FONT_GAME,"#ffff00");c.textAlign="left";c.x=e[0].x+a.width+10;c.y=e[0].y+a.height/2;c.textBaseline="middle";k.addChild(c);l.push(c);e[1]=createBitmap(a);e[1].x=
600;e[1].y=CANVAS_HEIGHT-90;k.addChild(e[1]);c=new createjs.Text("200","44px "+FONT_GAME,"#ffff00");c.textAlign="left";c.x=e[1].x+a.width+10;c.y=e[1].y+a.height/2;c.textBaseline="middle";k.addChild(c);l.push(c);e[2]=createBitmap(a);e[2].x=900;e[2].y=CANVAS_HEIGHT-90;k.addChild(e[2]);c=new createjs.Text("300","44px "+FONT_GAME,"#ffff00");c.textAlign="left";c.x=e[2].x+a.width+10;c.y=e[2].y+a.height/2;c.textBaseline="middle";k.addChild(c);l.push(c);h=[{x:440,y:129},{x:765,y:219},{x:1134,y:129},{x:450,
y:405},{x:1114,y:405}]};this.unload=function(){for(var a=0;5>a;a++)b[a].off("click",this._onBonusItemReleased)};this.show=function(d,c){f=c;a=!1;switch(d){case 3:g=BONUS_PRIZE[0];break;case 4:g=BONUS_PRIZE[1];break;case 5:g=BONUS_PRIZE[2];break;default:g=BONUS_PRIZE[0]}l[0].text="X"+g[0];l[1].text="X"+g[1];l[2].text="X"+g[2];for(var e=0;e<d;e++)b[e].visible=!0;k.visible=!0;createjs.Tween.get(k).to({alpha:1},1E3)};this._onBonusItemReleased=function(e,c){if(!a){a=!0;do var h=Math.floor(Math.random()*
s_aPrizeOccurence.length);while(g[s_aPrizeOccurence[h]]*f>SLOT_CASH);d=g[s_aPrizeOccurence[h]];b[c].gotoAndPlay("item_clicked");!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("choose_bonus_item");this.endBonus(c)}};this.endBonus=function(a){new CScoreText("X"+d,h[a].x,h[a].y);setTimeout(function(){k.alpha=0;k.visible=!1;for(var a=0;a<b.length;a++)b[a].visible=!1;s_oGame.endBonus(d)},4E3)};this._init()}
function CScoreText(a,d,f){var b;this._init=function(a,d,f){b=new createjs.Text("00000","50px "+FONT_GAME,"#ff0000");b.textAlign="center";b.text=a;b.x=d;b.y=f;b.alpha=0;b.shadow=new createjs.Shadow("#000000",2,2,2);s_oStage.addChild(b);var e=this;createjs.Tween.get(b).to({alpha:1},400,createjs.Ease.quadIn).call(function(){e.moveUp()})};this.moveUp=function(){var a=b.y-100,d=this;createjs.Tween.get(b).to({y:a},1E3,createjs.Ease.sineIn).call(function(){d.unload()})};this.unload=function(){s_oStage.removeChild(b)};
this._init(a,d,f)}
function CCreditsPanel(){var a,d,f,b,g,e,l,h,k,n;this._init=function(){n=new createjs.Container;n.alpha=0;s_oStage.addChild(n);var c=new createjs.Shape;c.graphics.beginFill("rgba(0,0,0,0.7)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);n.addChild(c);d=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));n.addChild(d);l=new createjs.Shape;l.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);l.alpha=.01;l.on("click",this._onLogoButRelease);n.addChild(l);c=s_oSpriteLibrary.getSprite("but_exit");a=
CANVAS_WIDTH/2+310;b=new CGfxButton(a,195,c,n);b.addEventListener(ON_MOUSE_UP,this.unload,this);e=new createjs.Text(TEXT_CREDITS_DEVELOPED,"40px "+FONT_GAME,"#000");e.textAlign="center";e.textBaseline="alphabetic";e.x=CANVAS_WIDTH/2;e.y=270;e.outline=2;n.addChild(e);g=new createjs.Text(TEXT_CREDITS_DEVELOPED,"40px "+FONT_GAME,"#fff");g.textAlign="center";g.textBaseline="alphabetic";g.x=CANVAS_WIDTH/2;g.y=270;n.addChild(g);c=s_oSpriteLibrary.getSprite("logo_ctl");f=createBitmap(c);f.regX=c.width/2;
f.regY=c.height/2;f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2;n.addChild(f);k=new createjs.Text("www.codethislab.com","34px "+FONT_GAME,"#000");k.textAlign="center";k.textBaseline="alphabetic";k.x=CANVAS_WIDTH/2;k.y=395;k.outline=2;n.addChild(k);h=new createjs.Text("www.codethislab.com","34px "+FONT_GAME,"#fff");h.textAlign="center";h.textBaseline="alphabetic";h.x=CANVAS_WIDTH/2;h.y=395;n.addChild(h);createjs.Tween.get(n).to({alpha:1},600,createjs.Ease.cubicOut);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};
this.refreshButtonPos=function(a,b){};this.unload=function(){l.off("click",this._onLogoButRelease);b.unload();b=null;s_oStage.removeChild(n)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en","_blank")};this._init()};
